### ISSUE TITLE
Add support for ngrock config file

### ISSUE THREAD

**Issue by spacedsweden** [kilmajster/ngrok-spring-boot-starter#43]
https://ngrok.com/docs#config

**Comment by kilmajster** [comment]
Hi @spacedsweden, thank you for reporting this issue 🙂 I just released version 0.2 that contains support for config files. If you're using `application.properties` based configuration, setup should looks like this:

```properties
ngrok.config=/home/user/ngrok-config.yml

or for multiple config files, use semicolon separator:

ngrok.config=/home/user/ngrok-config.yml;/home/user/ngrok-config-secondary.yml
```

Please let me know if this fixes your issue 😊

Regards,
Łukasz

**Comment by mabdelfattahm** [comment]
Can we add the support for classpath files ? Maybe copy the internal file to the same directory of ngrok2 ?

**Comment by kilmajster** [comment]
Hi @mabdelfattahm, please check if with v0.3.2 it works for you 😁 https://github.com/kilmajster/ngrok-spring-boot-starter#configuration-from-classpath
