### ISSUE TITLE
multiple domain 

### ISSUE THREAD

**Issue by alex-huang-dc** [kilmajster/ngrok-spring-boot-starter#45]
Hello,

I am looking for this plugin for a while. It is useful, but I have multiple domains and I wish I could specify the domain URL that I want to associate with ngrok.

**Comment by kilmajster** [comment]
Hi @alex-huang-dc! Thanks for your message, I am glad to see people making use of my project  🙂 I was thinking what could be the best solution for your and possible similar cases in the future, so in version 0.3.0 which I just released there is a possibility to provide your own arguments that will be passed to ngrok, so theorically you should be able to achieve any possible ngrok configuration. For more details see [example](https://github.com/kilmajster/ngrok-spring-boot-starter#ngrokcommand---ngrok-custom-command-attributes)

Please let me know if now you are able to get your domain configuration :)
