### ISSUE TITLE
Use @ConfigurationProperties instead of @Value for auto-completion

### ISSUE THREAD

**Issue by s-frei** [kilmajster/ngrok-spring-boot-starter#52]
Hey there,

just discovered your starter as I tought about exposing some ports using ngrok here and there,
and I am glad there is something around :wink: And it works 👍 

But I'd suggest to use configuration classes to have some auto-completion in the application configuration
to make the experience using this starter even better and avoid the need to search for the statics.

If you'd like me to, I could provide that. Tell me what you think about that.

**Comment by kilmajster** [comment]
H2 @s-frei, thanks for your idea! It sounds good to me so if you got time feel free to open a MR. Ask here if you need any help 🙂

**Comment by kilmajster** [comment]
Released in https://github.com/kilmajster/ngrok-spring-boot-starter/releases/tag/0.3.6
